//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Магазин_одежды
{
    using System;
    using System.Collections.Generic;
    
    public partial class Готовые_товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Готовые_товары()
        {
            this.Доставка = new HashSet<Доставка>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Код_Товары { get; set; }
        public Nullable<int> Код_Украшения { get; set; }
        public string Ресунок_украшения { get; set; }
        public Nullable<int> Код_Производители { get; set; }
    
        public virtual Производители Производители { get; set; }
        public virtual Товары Товары { get; set; }
        public virtual Украшения Украшения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Доставка> Доставка { get; set; }
    }
}
