//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Магазин_одежды
{
    using System;
    using System.Collections.Generic;
    
    public partial class Доставка
    {
        public int Код { get; set; }
        public Nullable<int> Код_Клиент { get; set; }
        public Nullable<int> Код_Готовые_товары { get; set; }
        public string Дата_доставки { get; set; }
        public string Время_доставки { get; set; }
    
        public virtual Готовые_товары Готовые_товары { get; set; }
        public virtual Клиент Клиент { get; set; }
    }
}
